/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by terrajet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type BillingRuleAttachmentObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	OrganizationName *string `json:"organizationName,omitempty" tf:"organization_name,omitempty"`
}

type BillingRuleAttachmentParameters struct {

	// ID of the billing rule.
	// +crossplane:generate:reference:type=github.com/nivraph/provider-jet-taikun/apis/billingrule/v1alpha1.Rule
	// +kubebuilder:validation:Optional
	BillingRuleID *string `json:"billingRuleId,omitempty" tf:"billing_rule_id,omitempty"`

	// +kubebuilder:validation:Optional
	BillingRuleIDRef *v1.Reference `json:"billingRuleIdRef,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	BillingRuleIDSelector *v1.Selector `json:"billingRuleIdSelector,omitempty" tf:"-"`

	// Discount rate in percents (0-100 %). Defaults to `100`.
	// +kubebuilder:validation:Optional
	DiscountRate *float64 `json:"discountRate,omitempty" tf:"discount_rate,omitempty"`

	// ID of the organisation.
	// +crossplane:generate:reference:type=github.com/nivraph/provider-jet-taikun/apis/organization/v1alpha1.Organization
	// +kubebuilder:validation:Optional
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// +kubebuilder:validation:Optional
	OrganizationIDRef *v1.Reference `json:"organizationIdRef,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	OrganizationIDSelector *v1.Selector `json:"organizationIdSelector,omitempty" tf:"-"`
}

// BillingRuleAttachmentSpec defines the desired state of BillingRuleAttachment
type BillingRuleAttachmentSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     BillingRuleAttachmentParameters `json:"forProvider"`
}

// BillingRuleAttachmentStatus defines the observed state of BillingRuleAttachment.
type BillingRuleAttachmentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BillingRuleAttachmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// BillingRuleAttachment is the Schema for the BillingRuleAttachments API
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,taikunjet}
type BillingRuleAttachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              BillingRuleAttachmentSpec   `json:"spec"`
	Status            BillingRuleAttachmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BillingRuleAttachmentList contains a list of BillingRuleAttachments
type BillingRuleAttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BillingRuleAttachment `json:"items"`
}

// Repository type metadata.
var (
	BillingRuleAttachment_Kind             = "BillingRuleAttachment"
	BillingRuleAttachment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BillingRuleAttachment_Kind}.String()
	BillingRuleAttachment_KindAPIVersion   = BillingRuleAttachment_Kind + "." + CRDGroupVersion.String()
	BillingRuleAttachment_GroupVersionKind = CRDGroupVersion.WithKind(BillingRuleAttachment_Kind)
)

func init() {
	SchemeBuilder.Register(&BillingRuleAttachment{}, &BillingRuleAttachmentList{})
}
