apiVersion: accessprofile.taikun.jet.crossplane.io/v1alpha1
kind: Profile
metadata:
  name: ACCESS_PROFILE
spec:
  forProvider:
    name: "ACCESS_PROFILE"
    organizationIdRef:
        name: "ORGANIZATION_REF"
  providerConfigRef:
    name: default
